Exposed interceptors property.
zhevron/odata pull request #1
Opened 2019-09-29 07:18 UTC by matracey

Added an interceptors property to ODataClient which exposes the underlying axios interceptors property. This is useful for setting pre- and post-request handlers.

2019-10-02 14:13 UTC, zhevron requested changes
Sorry for taking so long in getting to this. Thanks for submitting this! Just a couple of small fixes and it looks good to me.

2019-10-02 14:13 UTC, zhevron commented on lib/ODataClient.d.ts
> +        request: import("axios").AxiosInterceptorManager<AxiosRequestConfig>;
Would rather have the types imported at the top of the file instead of inline imports.

2019-10-02 14:13 UTC, zhevron commented on lib/ODataClient.d.ts
> +        response: import("axios").AxiosInterceptorManager<import("axios").AxiosResponse<any>>;
Would rather have the types imported at the top of the file instead of inline imports.

2019-10-23 06:56 UTC, matracey commented
Sorry it took me so long to get back to you. I missed notifications on this! I'm honestly not sure how I managed to go with inline Imports - I'd always favor having them at the top as well. I'll push a fix for this.

2019-10-23 22:58 UTC, matracey commented
Ok. I've made the change. The `.d.ts` file is auto-generated, so I'm not sure why it decided to use the inline imports instead of using the existing import declaration at the top of the file, but I've fixed that now anyway.

2019-10-24 08:57 UTC, zhevron approved these changes

2019-10-24 08:57 UTC, merged

2019-10-24 09:02 UTC, zhevron commented
Thanks for the PR! And I just noticed it does the same when I build locally. Guessing a TypeScript update caused it. Merged and published to npm.